function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "main.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

var jade_indent = [];
jade_debug.unshift(new jade.DebugItem( 0, "main.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "main.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "main.jade" ));
buf.push("\n<html lang=\"ru\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "main.jade" ));
buf.push("\n  <head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "main.jade" ));
buf.push("\n    <meta charset=\"UTF-8\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "main.jade" ));
buf.push("\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "main.jade" ));
buf.push("\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 7, "main.jade" ));
buf.push("\n    <link href=\"css/main.css\" rel=\"stylesheet\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "main.jade" ));
buf.push("\n    <title>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 8, jade_debug[0].filename ));
buf.push("Личный Сайт Аркадия Конопли");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "main.jade" ));
buf.push("\n  <body>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 11, "main.jade" ));
buf.push("\n    <div class=\"body\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 12, "main.jade" ));
buf.push("\n      <div class=\"header\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 13, "main.jade" ));
buf.push("\n        <div class=\"auth-button\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 13, jade_debug[0].filename ));
buf.push("Авторизация");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "main.jade" ));
buf.push("\n        <div class=\"clearfix\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n      </div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "main.jade" ));
buf.push("\n      <div class=\"container\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 16, "main.jade" ));
buf.push("\n        <div class=\"about\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 17, "main.jade" ));
buf.push("\n          <div class=\"verh\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 18, "main.jade" ));
buf.push("\n            <div class=\"avatar\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 19, "main.jade" ));
buf.push("<img src=\"images/avatar.jpg\" class=\"avatar-img\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 20, "main.jade" ));
buf.push("\n            <div class=\"name\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 21, "main.jade" ));
buf.push("\n              <h1 class=\"name-h1\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 21, jade_debug[0].filename ));
buf.push("Аркадий Конопля");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n            </div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 22, "main.jade" ));
buf.push("\n            <div class=\"kto\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 23, "main.jade" ));
buf.push("\n              <h3 class=\"kto-h3\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 23, jade_debug[0].filename ));
buf.push("Веб-разработчик");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n            </div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 24, "main.jade" ));
buf.push("\n            <div class=\"social\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 25, "main.jade" ));
buf.push("\n              <div class=\"icon-social\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 26, "main.jade" ));
buf.push("<img src=\"images/vk.svg\" class=\"vk-social\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 27, "main.jade" ));
buf.push("\n              <div class=\"icon-social\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(" ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 28, "main.jade" ));
buf.push("<img src=\"images/github.svg\" class=\"github-social\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 29, "main.jade" ));
buf.push("\n              <div class=\"icon-social\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 30, "main.jade" ));
buf.push("<img src=\"images/in.svg\" class=\"in-social\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n            </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n          </div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 31, "main.jade" ));
buf.push("\n          <div class=\"niz\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 32, "main.jade" ));
buf.push("\n            <div class=\"link-main\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 33, "main.jade" ));
buf.push("<a href=\"#\" class=\"a-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 34, "main.jade" ));
buf.push("\n                <div class=\"link link-works\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 34, jade_debug[0].filename ));
buf.push("Мои работы");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 35, "main.jade" ));
buf.push("<a href=\"#\" class=\"a-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 36, "main.jade" ));
buf.push("\n                <div class=\"link link-about\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 36, jade_debug[0].filename ));
buf.push("Обо Мне");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 37, "main.jade" ));
buf.push("<a href=\"#\" class=\"a-link\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 38, "main.jade" ));
buf.push("\n                <div class=\"link link-blog\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 38, jade_debug[0].filename ));
buf.push("Блог");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n          </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 39, "main.jade" ));
buf.push("\n        <div class=\"copy\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 39, jade_debug[0].filename ));
buf.push("&copy Аркадий Конопля | 2017");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 40, "main.jade" ));
buf.push("\n        <div class=\"about auth\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 41, "main.jade" ));
buf.push("\n          <div class=\"form\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n        </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n      </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n    </div>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </body>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n</html>");
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\r\nhtml(lang='ru')\r\n\thead\r\n\t\tmeta(charset='UTF-8')\r\n\t\tmeta(http-equiv='X-UA-Compatible', content=\"IE=edge,chrome=1\")\r\n\t\tmeta(name='viewport' content='width=device-width, initial-scale=1')\r\n\t\tlink(href=\"css/main.css\" rel=\"stylesheet\")\r\n\t\ttitle Личный Сайт Аркадия Конопли\r\n\r\n\tbody\r\n\t\t.body\r\n\t\t\t.header\r\n\t\t\t\t.auth-button Авторизация\r\n\t\t\t\t.clearfix\r\n\t\t\t.container\r\n\t\t\t\t.about\r\n\t\t\t\t\t.verh\r\n\t\t\t\t\t\t.avatar\r\n\t\t\t\t\t\t\timg.avatar-img(src=\"images/avatar.jpg\")\r\n\t\t\t\t\t\t.name\r\n\t\t\t\t\t\t\th1.name-h1 Аркадий Конопля\r\n\t\t\t\t\t\t.kto\r\n\t\t\t\t\t\t\th3.kto-h3 Веб-разработчик\r\n\t\t\t\t\t\t.social\r\n\t\t\t\t\t\t\t.icon-social\r\n\t\t\t\t\t\t\t\timg.vk-social(src='images/vk.svg')\r\n\t\t\t\t\t\t\t.icon-social \r\n\t\t\t\t\t\t\t\timg.github-social(src='images/github.svg')\r\n\t\t\t\t\t\t\t.icon-social\r\n\t\t\t\t\t\t\t\timg.in-social(src='images/in.svg')\r\n\t\t\t\t\t.niz\r\n\t\t\t\t\t\t.link-main\r\n\t\t\t\t\t\t\ta.a-link(href=\"#\")\r\n\t\t\t\t\t\t\t\t.link(class='link-works') Мои работы\r\n\t\t\t\t\t\t\ta.a-link(href=\"#\")\r\n\t\t\t\t\t\t\t\t.link(class='link-about') Обо Мне\r\n\t\t\t\t\t\t\ta.a-link(href=\"#\")\r\n\t\t\t\t\t\t\t\t.link(class='link-blog') Блог\r\n\t\t\t\t.copy &copy Аркадий Конопля | 2017\r\n\t\t\t\t.about(class='auth')\r\n\t\t\t\t\t.form\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
}
}